Tests/integration/admin user controller
BartoliniAndBorderCollies/Bike.v2_REST_API pull request #16
Opened 2023-11-21 16:36 UTC by BartoliniAndBorderCollies

#### Issue
https://trello.com/c/N2pHV7zA

### Description
This branch adds integration tests to cover `AdminUserController` class

### Changes introduced by this pull request
- add no args constructor to `ListUsersForAdminResponseDTO` class
- add all args constructor to `User` class
- add `cascade` to bike field in `User` class
- add integration tests to cover 100% of methods and 100% of lines in `AdminUserController`

### Testing
- [x] all tests are operational and run fine!

2023-11-24 00:26 UTC, JasinskiSz requested changes
Same issue imo as in the #15 - I'd like the names of those tests changed to something that is really tested inside.

2023-11-24 00:26 UTC, JasinskiSz commented on src/integration_test/java/com/klodnicki/Bike/v2/rest/controller/AdminUserControllerIntegrationTest.java
> +    public void deleteUser_ShouldDeleteUserFromDatabase_WhenUserIdIsGiven() {
This test naming and construction is looking fine.

2023-11-24 08:16 UTC, BartoliniAndBorderCollies commented
Ok please check now, but this one I haven't changed as for me it clearly describes what it does:
 public void banUser_ShouldReturnResponseEntityAsStringAndSetAccountValidToFalse_WhenUserIdIsGiven()

2023-11-26 11:13 UTC, JasinskiSz approved these changes
That's fine

2023-11-26 11:44 UTC, merged